### ISSUE TITLE
PLUGIN NOT ACTIVATED

### ISSUE THREAD

**Issue by hardsiamang655** [LOCM-Team/LSkyBlock#1]
17:14:12 [ERROR] Throwing
java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/json/JSONObject
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:440) [Nukkit.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:750) [Nukkit.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:739) [Nukkit.jar:?]
        at cn.nukkit.Server.<init>(Server.java:582) [Nukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [Nukkit.jar:?]
Caused by: java.lang.NoClassDefFoundError: org/json/JSONObject
        at com.larryTheCoder.schematic.IslandBlock.setSign(IslandBlock.java:193) ~[?:?]
        at com.larryTheCoder.schematic.SchematicHandler.handleSchematic(SchematicHandler.java:470) ~[?:?]
        at com.larryTheCoder.schematic.SchematicHandler.<init>(SchematicHandler.java:422) ~[?:?]
        at com.larryTheCoder.ASkyBlock.registerObject(ASkyBlock.java:237) ~[?:?]
        at com.larryTheCoder.ASkyBlock.onEnable(ASkyBlock.java:139) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[Nukkit.jar:?]
        ... 4 more
Caused by: java.lang.ClassNotFoundException: org.json.JSONObject
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28) ~[Nukkit.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at com.larryTheCoder.schematic.IslandBlock.setSign(IslandBlock.java:193) ~[?:?]
        at com.larryTheCoder.schematic.SchematicHandler.handleSchematic(SchematicHandler.java:470) ~[?:?]
        at com.larryTheCoder.schematic.SchematicHandler.<init>(SchematicHandler.java:422) ~[?:?]
        at com.larryTheCoder.ASkyBlock.registerObject(ASkyBlock.java:237) ~[?:?]
        at com.larryTheCoder.ASkyBlock.onEnable(ASkyBlock.java:139) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[Nukkit.jar:?]
        ... 4 more
17:14:12 [INFO ] Disabling ASkyBlock v0.5.2-BETA

**Comment by hardsiamang655** [comment]
s
